site_name: gotmpl
site_url: https://gotmpl.dev
site_description: The power of Go templates, without compromise.

repo_name: gotmpl/gotmpl
repo_url: https://github.com/gotmpl/gotmpl

edit_uri: edit/main/docs

extra:
  version: "0.0.0"
  go_version: "1.25"

theme:
  name: material
  logo: static/icon.png
  favicon: static/favicon.ico
  icon:
    annotation: material/star-four-points-circle
  custom_dir: docs/overrides
  language: en
  features:
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.tabs.link
    - content.code.copy
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme)" # System mode
      toggle:
        icon: material/routine
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" # Light mode
      scheme: default
      primary: black
      accent: indigo
      example: "#ddd"
      toggle:
        icon: material/light-mode
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # Dark mode
      scheme: slate
      primary: black
      accent: indigo
      example: "#ddd"
      toggle:
        icon: material/dark-mode
        name: Switch to system mode
  include_search_page: false
  search_index_only: true

plugins:
  - search
  - macros

markdown_extensions:
  - meta
  - md_in_html
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.saneheaders
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.blocks.html
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      toc_depth: 3
      permalink: true

nav:
  - Getting Started:
      - Introduction: introduction.md
      - Installation: installation.md
      - Usage: usage.md
  - Features:
      - Variables: features/variables.md
      - Functions: features/functions.md
      - Environments: features/environments.md
  - Development:
      - Releases: development/releases.md
      - Roadmap: development/roadmap.md
not_in_nav: index.md

copyright: >
  Made with 🩶 by the
  <a href="https://github.com/gotmpl/gotmpl/graphs/contributors" target="_blank" rel="noopener">
    gotmpl contributors
  </a>
