name: build

on:
  push:
    branches:
      - master
      - release/*
  pull_request:

permissions:
  contents: write
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - run: git --version

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - run: go version

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - run: docker buildx version

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.10.0

      - run: cosign version

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.20.6

      - run: syft version

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: "goreleaser"
          version: "~> v2.12.0"
          install-only: true

      - run: goreleaser --version

      - run: goreleaser check
      - run: goreleaser healthcheck

      - name: Build
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: goreleaser release --clean --snapshot --skip=publish
